# -*- coding: utf-8 -*-
"""Rule based chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wBscJ2A4p4Zzm3Jnetf6LasNPFKcbXcy
"""

dictionary = {
    "hello": "Hi there! How can I help you?",
    "hi": "Hello! How can I help you? ",
    "hey": "Hi! What's up?",
    "how are you": "I'm doing great!",
    "what's up":"Answering your quries",
    "who are you": "I am rule based chatbot",
    "what are you doing right now": "Answering your quries",
    "what is ai": "AI stands for Artificial Intelligence.",
    "what is your name": "I'm a rule-based AI chatbot.",
    "thanks": "You're welcome!"
}

while True:
      userinput= input("You:")
      userinput=userinput.lower().strip()

      if userinput== "bye" or userinput=="exit" or userinput=="quit":
       print("Bot: Goodbye")
       break
      response=dictionary.get(userinput,"I don't understant that")
      print("Bot:",response)